version: '3.5'
services:
    db:
      image: postgres:alpine
      restart: always
      environment:
        POSTGRES_USER: postgres
        POSTGRES_PASSWORD: '1234'
        POSTGRES_DB: bankapp
      ports:
        - "5432:5432"
      volumes: 
        - db:/var/lib/postgresql/data

    bankapp-project:
      build:
        context: ./ClevertecBanksApp
      container_name: bankapp-project
      restart: always
      ports:
        - "8080:8080"
      depends_on:
        - db      
volumes:
  db:


